image: pavelyanu/yanushonak:latest

stages:
  - test
  - build
  - deploy

run tests:
  stage: test
  script:
    - python -m unittest discover tests

build:
  stage: build
  script:
    - pip install setuptools wheel
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/*

deploy:
  stage: deploy
  script:
    - pip install twine
    - twine upload --repository-url https://upload.pypi.org/legacy/ --username $PYPI_USERNAME --password $PYPI_PASSWORD dist/*
  only:
    - master
